"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mkr__factory = exports.Dai__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Dai__factory_1 = require("./Dai__factory");
Object.defineProperty(exports, "Dai__factory", { enumerable: true, get: function () { return Dai__factory_1.Dai__factory; } });
var Mkr__factory_1 = require("./Mkr__factory");
Object.defineProperty(exports, "Mkr__factory", { enumerable: true, get: function () { return Mkr__factory_1.Mkr__factory; } });
