"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProxyStandardStorageSlot__factory = exports.ProxyCustomImplementation__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ProxyCustomImplementation__factory_1 = require("./ProxyCustomImplementation__factory");
Object.defineProperty(exports, "ProxyCustomImplementation__factory", { enumerable: true, get: function () { return ProxyCustomImplementation__factory_1.ProxyCustomImplementation__factory; } });
var ProxyStandardStorageSlot__factory_1 = require("./ProxyStandardStorageSlot__factory");
Object.defineProperty(exports, "ProxyStandardStorageSlot__factory", { enumerable: true, get: function () { return ProxyStandardStorageSlot__factory_1.ProxyStandardStorageSlot__factory; } });
