/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProxyCustomImplementation__factory } from "./ProxyCustomImplementation__factory";
export { ProxyStandardStorageSlot__factory } from "./ProxyStandardStorageSlot__factory";
